name: rural_e_commerce
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  google_sign_in: ^4.5.1
  provider: ^3.1.0
  flutter_spinkit: ^4.1.2+1
  geolocator: ^5.3.2+2
  location: ^3.0.1
  flutter_map: ^0.10.1
  permission_handler: ^5.0.1+1
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.0
  string_utils: ^0.2.3 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.5"

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icon.jpg
    - assets/bottom.png
    - assets/farmer.png
    - assets/retailer.png
    - assets/google_logo.png
    - lang/en.json
    - lang/hi.json
    - lang/pa.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.jpg"